<a href="https://colab.research.google.com/github/kurokiasahi222/Uplimit-Intermediate-SQL/blob/main/Week_1_Project_Intermediate_SQL_March_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> 1. DUPLICATE THIS COLAB TO START WORKING ON IT. Using File > Save a copy to drive.
> 2. SHARE SETTINGS: In the new notebook, click "Share" in the top right corner and set the sharing settings to "Anyone with the link" ("Commenter" role).




Welcome to this first week's project for *Intermediate SQL*!

This week's lecture and material on Uplimit showed you how to write simple SQL queries from a single table. For this project we further your understanding of these concepts by delving a bit deeper. However, for everything covered in this project you can find related examples in our course material.

# **Prerequisite Configuration - RUN THESE CELLS BEFORE STARTING**
Below we install the software required to run this project. Please make sure to **RUN IT** by clicking on the play-button icon and to feel free to ignore the content of these two hidden cells.

**IMPORTANT:** These cells may have to be rerun every time you are away from the notebook a long time or access notebook on a different browser or a different laptop. If you see an error that says
"NameError: name 'run' is not defined" you need to run these two hidden cells again.

In [2]:
%%capture
!pip install git+https://github.com/uplimit/course-intermediate-sql.git

In [3]:
import pandas as pd
from IPython.display import display, HTML
from sql_course import run as sql_run
from sql_course import check

# Show all the rows (instead of only a few)
pd.set_option("display.max_rows", None)

# Set precision to max 2 decimals
pd.set_option('display.precision', 2)

# Set CSS Style for Table
# Make it work with night & light mode
# - Alternating rows
# - th elements
# - td elements
css_style = '''
<style>
  html {
    --td-font-color: black;
    --font-color: black;
    --background-color: #e0e0e0;
  }
  html[theme=dark] {
    --td-font-color: white;
    --font-color: black;
    --background-color: #6688ff;
  }
  th {
    background: #fbd44c;
    color: var(--font-color);
    font-size: 16px;
    text-align: center;
    font-weight: bold;
  }
  tr:nth-child(even) {
    background-color: var(--background-color);
    color: var(--font-color);
  }
  td {
    font-size: 14px;
    color: var(--td-font-color);
  }
</style>
'''


def run(sql_query):
  df = sql_run(sql_query)

  # Puts the scrollbar next to the DataFrame
  display(HTML(css_style +
               "<div style='max-height: 500px; overflow: auto; width: fit-content; border-style: solid;" +
               " border-width: 1px; border-color: #0139fe; font-family: GT Planar,Inter,Arial,sans-serif;'>" +
               df.style.to_html() +
               "</div>"))

# **The Setting:**

Congratulations! You got yourself a new shiny job as the analyst at Uplimit.

Here is what you need to know about the Uplimit business to be able to complete this project. As you know, Uplimit conducts plenty of courses such as *Intermediate SQL* and runs them several times in a year typically. Uplimit wants to run these courses across several categories (such as Machine Learning, Data Engineering) and at different levels (Beginner vs Advanced). Each course is typically run for a few weeks (ranging from a 1- or 2-week crash course all the way to an extended 10-week course). Each course is facilitated by a small number of teaching assistants who help with conducting office hours as well as help answering questions on the project. Finally and most importantly, each course has a nps (net promoter score) rating which is based on what percentage of the class thinks very highly of the course and would recommend it without reservations. NPS Score range from 0 to 100

# **Schema:**

![week1_erdiagram.png]()

# **Create Table Statement:**

The table you will be working on was created with the following create statement (you do not have to create this table and it is already pre-loaded):



```
CREATE TABLE courses (
  course_id INTEGER,
  course_name TEXT,
  course_desc TEXT,
  course_category TEXT,
  course_level TEXT,
  start_date DATE,
  num_weeks INTEGER,
  num_learners_registered INTEGER,
  num_TAs INTEGER,
  nps INTEGER
);
```

# **Disclaimer**

Any resemblance of the data in this table to anything real (other than the names and descriptions of courses) are entirely random (could have been my pseudo random generator or my own imagination, since it isn't easy to distinguish between the two :-), so do not stress yourself out trying to make sense of any categorization, such as why a course run might even overlap with another run and such other niceties).

# **Part 0 - Running and Testing Queries - An Example:**

To access the data contained in the courses table, you need to write SQL between three quotation marks, like:

```
query = """
        SELECT *
        FROM courses
        """
run(query)
check(q0_0_1 = query)
```

Then that SQL is pulled through a `run()`-command and a `check()`-command so that you can see the output of the SQL query, and whether you wrote the expected query. This you can see after the output. If you've done it correctly, you'll see **"Your SQL query is correct!"**.

In [4]:
### Question: q0_0_1
### This is just a test query to demonstrate how you will be submitting your SQL queries.
### It also allows you to browse the data bit.
query = """
        SELECT *
        FROM courses
        """

run(query)
check(q0_0_1 = query)

-------------------
Your SQL query is correct!

# **Part 1 - Basics of the Business:**


Let's now fast-forward several years into your career at Uplimit. It is the year 2024. The `courses` table has courses that have run up until now (in 2024).

 Your database has been humming along nicely, and Uplimit has just hired a new head of content creation. They are very curious about the historical data and want to understand the basics of Uplimit business and want some basic information from the courses table. Your task is to help them answer these questions they have:

In [5]:
### Question: q0_1_1
### How many courses have we run so far?
### (This is the number of rows in the table as all courses in the table have been run as you are in 2024).
### Output columns: cnt
query = """
  SELECT COUNT(*) AS cnt
  FROM courses
  """

run(query)
check(q0_1_1 = query)

-------------------
Your SQL query is correct!

In [6]:
### Question: q0_1_3
### Getting into some more details, they would like to know:
### What are the distinct categories of courses that we run?
### We do not want the same category to be returned multiple times as it makes the output messy.
### Please do not use the GROUP BY clause in your answer.
### This is to understand the spectrum of courses we cover - categories give you an idea of what all topics we cover.
### Output columns: course_category
query = """
  SELECT DISTINCT course_category
  FROM courses
  """

run(query)
check(q0_1_3 = query)

-------------------
Your SQL query is correct!

In [7]:
### Question: q0_1_4
### For the course category 'Machine Learning', how many courses have we run so far?
### Output columns: cnt
query = """
  SELECT COUNT(*) AS cnt
  FROM courses
  WHERE course_category = 'Machine Learning'
  """

run(query)
check(q0_1_4 = query)

-------------------
Your SQL query is correct!

In [8]:
### Question: q0_1_5
### What are the distinct course categories for which there are courses that have run for more than 2 weeks and had more than 4 TAs
### Output columns: course_category
query = """
  SELECT DISTINCT course_category
  FROM courses
  WHERE num_weeks > 2 AND num_TAs > 4
  """

run(query)
check(q0_1_5 = query)

-------------------
Your SQL query is correct!

The following query is to mainly get you acquainted with complex logical expressions involving AND, OR and NOT.

In [9]:
run('''SELECT * FROM courses''')

In [10]:
### Question: q0_1_6
### What are the distinct course names corresponding to runs of courses for which
### either i) they had a nps of greater than 85 and had more than 3 TAS
### or ii) it is not the case that at least one of the following holds:
###        a) course_category is 'Machine Learning' or b) num_tas is less than 5
### Output columns: course_name
query = """
  SELECT DISTINCT(course_name)
  FROM courses
  WHERE (nps > 85 AND num_TAs > 3)
  OR (NOT (course_category = "Machine Learning" or num_tas < 5))
  """

run(query)
check(q0_1_6 = query)

-------------------
Your SQL query is correct!

# **Part 2 - Looking for pockets of extreme performance on NPS:**

The head of content creation would like to understand the distribution of nps overall to get their bearings (recall that this is the most important metric for the business).

In [11]:
### Question: q0_2_1
### Find the minimum, maximum, and average of nps across all courses
### Output columns: min_nps, max_nps, avg_nps
query = """
  SELECT
    MIN(nps) AS min_nps,
    MAX(nps) AS max_nps,
    AVG(nps) AS avg_nps
  FROM courses
  """

run(query)
check(q0_2_1 = query)

-------------------
Your SQL query is correct!

We would now like to understand the nps distribution per course category - this will throw more light on if some categories routinely tend to do better than others.

In [12]:
column_name = lambda: run("SELECT * FROM courses WHERE 1=0")

In [13]:
### Question: q0_2_2
### Find the minimum, maximum, and average  of nps for each course category
### Output columns: course_category, min_nps, max_nps, avg_nps
query = """
  SELECT
    course_category,
    MIN(nps) AS min_nps,
    MAX(nps) AS max_nps,
    AVG(nps) AS avg_nps
  FROM courses
  GROUP BY course_category
"""

run(query)
check(q0_2_2 = query)

-------------------
Your SQL query is correct!

In [14]:
column_name()

In [15]:
### Question: q0_2_3
### Find the minimum, maximum, and average  of nps for each course category provided
### the course did not run for more than 6 weeks
### Output columns: course_category, min_nps, max_nps, avg_nps
query = """
  SELECT
    course_category,
    MIN(nps) AS min_nps,
    MAX(nps) AS max_nps,
    AVG(nps) AS avg_nps
  FROM courses
  WHERE num_weeks < 7
  GROUP BY course_category
  """

run(query)
check(q0_2_3 = query)

-------------------
Your SQL query is correct!

We would now like to restrict the above output only to categories that have more than 3 distinct courses (with different names) that have been run.

In [16]:
column_name()

In [17]:
### Question: q0_2_4
### Find the minimum, maximum, and average  of nps for each course category
### that has more than 3 distinct courses (course names) as part of that category
### Output columns: course_category, min_nps, max_nps, avg_nps
query = """
  SELECT
    course_category,
    MIN(nps) AS min_nps,
    MAX(nps) AS max_nps,
    AVG(nps) AS avg_nps
  FROM courses
  GROUP BY course_category
  HAVING COUNT(DISTINCT (course_name)) > 3
  """

run(query)
check(q0_2_4 = query)

-------------------
Your SQL query is correct!

# **Part 3 - Bonus Question:**

Your task is to write an SQL query that calculates, for each course category:

- The average ratio of learners to TAs for all course runs in that category. This is a derived value calculated by dividing the total number of learners by the number of TAs for each course run.
- The average duration in weeks for all course runs in that category.

In [18]:
### Question: q0_3_1
### For each course_category, print the average learner to TA ratio
### and the average number of weeks for the course runs belonging to that category.
### Hint: You can create derived columns by dividing one column with another. In addition, you can aggregate derived columns.
### Please put the integer columns inside a CAST operator to make it a float.
### If you are dividing two integers but would like the result to be a float.
### Output columns: course_category, avg_learner_ta_ratio, avg_num_weeks
query = """
  SELECT
    course_category,
    AVG(num_learners_registered / CAST(num_TAs AS FLOAT)) AS avg_learner_ta_ratio,
    AVG(num_weeks) AS avg_num_weeks
  FROM courses
  GROUP BY course_category
  """

run(query)
check(q0_3_1 = query)

-------------------
Your SQL query is correct!

Hints
- To create a derived column by dividing one column by another, ensure you CAST at least one operand to a float to avoid integer division.
- You can use the AVG() function to calculate both the average learner-to-TA ratio and the average duration in weeks, GROUP BY course_category.

# **Conclusion:** That was some fantastic work! Your SQL skills are really getting polished, and you're now ready for the tests ahead of you involving multiple tables.